name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload  # ★ 必須
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}         # PR コメント等に利用（任意だが推奨）
          app_location: "/"                               # リポジトリアプリのルート
          output_location: ".next"                        # Next.js（SSR/ISR）は .next を指定
          api_location: ""                                # Functions 使うなら "api"
          # is_static_export, skip_app_build などは書かない
