name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 依存を入れておく（Oryxでもやってくれるが安定のため）
      - name: Install deps
        run: npm ci

      # ← ここで “next build” をわざわざ叩かなくてOK（Oryxがやる）

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"          # リポジトリのアプリルート
          output_location: ".next"   # Next.js SSR/ISR は .next を指定
          api_location: ""           # Functions を使う場合は "api"
        # ★ skip_app_build, app_artifact_location, is_static_export は指定しない
